// settings-dom.js
export function buildDomCache() {
    return {
        // Theme Editor
        editorModal: document.getElementById('theme-editor-modal'),
        editorGrid: document.getElementById('color-grid'),
        ftContainer: document.getElementById('fine-tune-container'),
        ftToggle: document.getElementById('toggle-fine-tune'),
        ftPreview: document.getElementById('fine-tune-preview'),
        ftHue: document.getElementById('ft-hue'),
        ftSat: document.getElementById('ft-sat'),
        ftLit: document.getElementById('ft-lit'),
        targetBtns: document.querySelectorAll('.target-btn'),
        edName: document.getElementById('theme-name-input'),
        edPreview: document.getElementById('theme-preview-box'),
        edPreviewBtn: document.getElementById('preview-btn'),
        edPreviewCard: document.getElementById('preview-card'),
        edSave: document.getElementById('save-theme-btn'),
        edCancel: document.getElementById('cancel-theme-btn'),
        openEditorBtn: document.getElementById('open-theme-editor'),

        // Voice Preset
        voicePresetSelect: document.getElementById('voice-preset-select'),
        voicePresetAdd: document.getElementById('voice-preset-add'),
        voicePresetSave: document.getElementById('voice-preset-save'),
        voicePresetRename: document.getElementById('voice-preset-rename'),
        voicePresetDelete: document.getElementById('voice-preset-delete'),
        voicePitch: document.getElementById('voice-pitch'),
        voiceRate: document.getElementById('voice-rate'),
        voiceVolume: document.getElementById('voice-volume'),
        voiceTestBtn: document.getElementById('test-voice-btn'),
        voiceSection: document.getElementById('voice-settings-section'),
        voiceSelect: document.getElementById('voice-select'),

        // Core Settings UI
        settingsModal: document.getElementById('settings-modal'),
        themeSelect: document.getElementById('theme-select'),
        themeAdd: document.getElementById('theme-add'),
        themeRename: document.getElementById('theme-rename'),
        themeDelete: document.getElementById('theme-delete'),
        themeSave: document.getElementById('theme-save'),
        configSelect: document.getElementById('config-select'),
        quickConfigSelect: document.getElementById('quick-config-select'),
        configAdd: document.getElementById('config-add'),
        configRename: document.getElementById('config-rename'),
        configDelete: document.getElementById('config-delete'),
        configSave: document.getElementById('config-save'),

        // Core Toggles & Inputs
        input: document.getElementById('input-select'),
        mode: document.getElementById('mode-select'),
        practiceMode: document.getElementById('practice-mode-toggle'),
        machines: document.getElementById('machines-select'),
        seqLength: document.getElementById('seq-length-select'),
        autoClear: document.getElementById('autoclear-toggle'),
        autoplay: document.getElementById('autoplay-toggle'),
        flash: document.getElementById('flash-toggle'),
        pause: document.getElementById('pause-select'),
        audio: document.getElementById('audio-toggle'),
        hapticMorse: document.getElementById('haptic-morse-toggle'),
        playbackSpeed: document.getElementById('playback-speed-select'),
        chunk: document.getElementById('chunk-select'),
        delay: document.getElementById('delay-select'),
        haptics: document.getElementById('haptics-toggle'),
        speedGesturesToggle: document.getElementById('speed-gestures-toggle'),
        volumeGesturesToggle: document.getElementById('volume-gestures-toggle'),
        deleteGestureToggle: document.getElementById('delete-gesture-toggle'),
        clearGestureToggle: document.getElementById('clear-gesture-toggle'),
        autoTimerToggle: document.getElementById('auto-timer-toggle'),
        autoCounterToggle: document.getElementById('auto-counter-toggle'),
        arModeToggle: document.getElementById('ar-mode-toggle'),
        voiceInputToggle: document.getElementById('voice-input-toggle'),
        wakeLockToggle: document.getElementById('wake-lock-toggle'),
        upsideDownToggle: document.getElementById('upside-down-toggle'),
        speedDelete: document.getElementById('speed-delete-toggle'),
        showWelcome: document.getElementById('show-welcome-toggle'),
        blackoutToggle: document.getElementById('blackout-toggle'),
        stealth1KeyToggle: document.getElementById('stealth-1key-toggle'),
        longPressToggle: document.getElementById('long-press-autoplay-toggle'),
        blackoutGesturesToggle: document.getElementById('blackout-gestures-toggle'),
        timerToggle: document.getElementById('timer-toggle'),
        counterToggle: document.getElementById('counter-toggle'),
        gestureToggle: document.getElementById('gesture-input-toggle'),
        uiScale: document.getElementById('ui-scale-select'),
        seqSize: document.getElementById('seq-size-select'),
        seqFontSize: document.getElementById('seq-font-size-select'),
        gestureMode: document.getElementById('gesture-mode-select'),
        autoInput: document.getElementById('auto-input-select'),
        quickLang: document.getElementById('quick-lang-select'),
        generalLang: document.getElementById('general-lang-select'),
        closeSettingsBtn: document.getElementById('close-settings'),

        // Tabs
        tabs: document.querySelectorAll('.tab-btn'),
        contents: document.querySelectorAll('.tab-content'),

        // Modals & Overlays
        helpModal: document.getElementById('help-modal'),
        setupModal: document.getElementById('game-setup-modal'),
        shareModal: document.getElementById('share-modal'),
        closeSetupBtn: document.getElementById('close-game-setup-modal'),
        quickSettings: document.getElementById('quick-open-settings'),
        quickHelp: document.getElementById('quick-open-help'),
        quickAutoplay: document.getElementById('quick-autoplay-toggle'),
        quickAudio: document.getElementById('quick-audio-toggle'),
        dontShowWelcome: document.getElementById('dont-show-welcome-toggle'),
        quickResizeUp: document.getElementById('quick-resize-up'),
        quickResizeDown: document.getElementById('quick-resize-down'),
        openShareInside: document.getElementById('open-share-button'),
        closeShareBtn: document.getElementById('close-share'),
        closeHelpBtn: document.getElementById('close-help'),
        closeHelpBtnBottom: document.getElementById('close-help-btn-bottom'),
        openHelpBtn: document.getElementById('open-help-button'),
        promptDisplay: document.getElementById('prompt-display'),
        copyPromptBtn: document.getElementById('copy-prompt-btn'),
        generatePromptBtn: document.getElementById('generate-prompt-btn'),
        restoreBtn: document.querySelector('button[data-action="restore-defaults"]'),

        // Calibration
        calibModal: document.getElementById('calibration-modal'),
        openCalibBtn: document.getElementById('open-calibration-btn'),
        closeCalibBtn: document.getElementById('close-calibration-btn'),
        calibAudioSlider: document.getElementById('calib-audio-slider'),
        calibCamSlider: document.getElementById('calib-cam-slider'),
        calibAudioBar: document.getElementById('calib-audio-bar'),
        calibCamBar: document.getElementById('calib-cam-bar'),
        calibAudioMarker: document.getElementById('calib-audio-marker'),
        calibCamMarker: document.getElementById('calib-cam-marker'),
        calibAudioVal: document.getElementById('audio-val-display'),
        calibCamVal: document.getElementById('cam-val-display'),

        // Redeem & Donate
        redeemModal: document.getElementById('redeem-modal'),
        openRedeemBtn: document.getElementById('open-redeem-btn'),
        closeRedeemBtn: document.getElementById('close-redeem-btn'),
        redeemImg: document.getElementById('redeem-img'),
        redeemPlus: document.getElementById('redeem-zoom-in'),
        redeemMinus: document.getElementById('redeem-zoom-out'),
        openDonateBtn: document.getElementById('open-donate-btn'),
        openRedeemSettingsBtn: document.getElementById('open-redeem-btn-settings'),
        donateModal: document.getElementById('donate-modal'),
        closeDonateBtn: document.getElementById('close-donate-btn'),
        btnCashMain: document.getElementById('btn-cashapp-main'),
        btnPaypalMain: document.getElementById('btn-paypal-main'),

        // Sharing Buttons
        copyLinkBtn: document.getElementById('copy-link-button'),
        nativeShareBtn: document.getElementById('native-share-button'),
        chatShareBtn: document.getElementById('chat-share-button'),
        emailShareBtn: document.getElementById('email-share-button'),

        // Mapping & Mappings Containers
        mapping9Container: document.getElementById('mapping-9-container'),
        mapping12Container: document.getElementById('mapping-12-container'),
        mappingPianoContainer: document.getElementById('mapping-piano-container'),
        morseContainer: document.getElementById('morse-container'),

        // Gestures UI
        gestureTapSlider: document.getElementById('gesture-tap-slider'),
        gestureSwipeSlider: document.getElementById('gesture-swipe-slider'),
        gestureTapVal: document.getElementById('gesture-tap-val'),
        gestureSwipeVal: document.getElementById('gesture-swipe-val'),

        devSection: document.getElementById('dev-section'),
        devVoiceToggle: document.getElementById('dev-hide-voice-toggle'), // Updated to match your HTML
        devHapticToggle: document.getElementById('dev-hide-haptic-toggle'), // Updated to match your HTML
        // Header Elements
        headerGestureBtn: document.getElementById('header-gesture-btn'),
        headerStealthBtn: document.getElementById('header-stealth-btn'),
        headerHandBtn: document.getElementById('header-hand-btn')
    };
}